
services:
  redis:
    image: redis:latest
    container_name: leetcode-redis
    ports:
      - "6379:6379"
    restart: always

  mongodb:
    image: mongo:latest
    container_name: leetcode-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  executor:
    build: ../executor
    container_name: leetcode-executor
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sandbox:/sandbox
    restart: always

volumes:
  mongo-data:

networks:
  default:
    name: leetcode-network
